stages:
  - compile
  - build
  - deploy
  - cleanup

variables:
  NAMESPACE: "newpl1"
  IMAGE_REGISTRY: "registery.fardup.ir:5000"

.default-job:
  tags:
    - sharemodel-ci
  only:
    - newpl1

before_script:
  - export IMAGE_PROJECT="$(basename $(dirname $CI_PROJECT_DIR))/$(basename $CI_PROJECT_DIR)"
  - export COMMIT_ID=$(git log -1 --pretty=format:%h)
  - export GIT_TAG=$(git describe --exact-match --tags 2>/dev/null || echo "")
  - export IMAGE_TAG="${IMAGE_REGISTRY}/${IMAGE_PROJECT}:${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}${GIT_TAG:+_${GIT_TAG}}"
  - echo "IMAGE_TAG → $IMAGE_TAG"

compile-job:
  stage: compile
  extends: .default-job
  script:
    - export NVM_DIR="$HOME/.nvm"
    - [ -s "$NVM_DIR/nvm.sh" ]
    - \. "$NVM_DIR/nvm.sh"
    - nvm use 22
    - npm i -g npm
    - npm config set registry https://registry.npmjs.org/
    - npm ci --verbose
    - npm run build
  artifacts:
    paths:
      - .next/standalone
      - .next/static
      - public

build-Docker-job:
  stage: build
  extends: .default-job
  dependencies:
    - compile-job
  script:
    - docker build -t "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"

deploy-job:
  stage: deploy
  extends: .default-job
  environment: production
  dependencies:
    - build-Docker-job
  script:
    - envsubst < /home/gitlab-runner/ali-ci/newpl1/psya-client/psya-client.yaml > deployment.yaml
    - kubectl apply -f deployment.yaml -n "$NAMESPACE"

cleanup:
  stage: cleanup
  extends: .default-job
  script:
    - echo "Cleaning up project directory"
    - rm -rf "$CI_PROJECT_DIR"